#!/bin/bash
# kill script after defined minutes
#{
#    sleep 80m
#    kill $$
#} &

mkdir /tmp/ci/build_artifacts
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
source build/envsetup.sh
lunch lineage_tissot-user
export BUILD_TYPE=OFFICIAL
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 25G
ccache -o compression=true
ccache -z

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	mka bacon -j16
}

make_metalava
make_rom

# Copy build artifacts to ci dir for uploading on ci
cp out/target/product/tissot/*.zip /tmp/ci/build_artifacts/
cp out/target/product/tissot/*.zip /tmp/ci/build_artifacts/
