#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Fstrim
sudo sh -c "fstrim -Av"

# Normal build steps
. build/envsetup.sh
lunch lineage_tissot-user
#export SELINUX_IGNORE_NEVERALLOWS=true
export BUILD_TYPE="${BUILD_TYPE}"
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 30G
#ccache -o compression=true
#ccache -z

up(){
#    curl --upload-file $1 https://transfer.sh/
    curl --upload-file $1 https://oshi.at/$(basename $1); echo # 14 days, 10 GB limit
}

make_metalava(){
	mka api-stubs-docs -j16
	mka system-api-stubs-docs -j16
	mka test-api-stubs-docs -j16
}

make_rom(){
	mka bacon -j30
	zip=$(up out/target/product/tissot/*zip)
	echo ""
	echo "$zip"
}

#make_metalava
make_rom
