#!/bin/bash
# Lets see machine specifications and environments
echo "CPUs: "
nproc --all
echo "RAM: "
free -h
echo "Diskusage: "
df -h
echo "Enviornment: "
cat /etc/os*
env
# Check persistent folder for contents
echo "Cache: "
ls -lh /tmp/ccache
echo "Out: "
ls -lh /tmp/rom/out
