#!/bin/bash

MANIFEST="https://github.com/PixelExperience/manifest"
BRANCH="eleven-plus"

# Fstrim
#sudo sh -c "fstrim -Av"

# cd to working dir
mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name harveyspectar
git config --global user.email ultimatepravin72@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
#repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || 
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Clone extra repos, device side repos and extra ones
# Trees
echo "Cloning device side stuff!"
git clone https://github.com/harveyspectar/android_device_xiaomi_phoenix device/xiaomi/phoenix --single-branch --depth=1
#git clone https://github.com/harveyspectar/android_device_xiaomi_phoenix device/xiaomi/phoenix --single-branch --depth=1
git clone https://github.com/harveyspectar/android_device_xiaomi_sm6150-common device/xiaomi/sm6150-common --single-branch --depth=1
#git clone https://github.com/harveyspectar/android_device_xiaomi_sm6150-common device/xiaomi/sm6150-common --single-branch --depth=1
git clone https://github.com/harveyspectar/oss_kernel_xiaomi_sm6150 --single-branch --depth=1
git clone https://github.com/crdroidandroid/proprietary_vendor_xiaomi/ -b 11.0-phoenix vendor/xiaomi --single-branch --depth=1
git clone https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi --single-branch --depth=1
rm -rf vendor/xiaomi/miuicamera
git clone https://github.com/AtomicXZ/vendor_xiaomi_miuicamera vendor/xiaomi/miuicamera --single-branch --depth=1
#Hals
#rm -rf hardware/qcom-caf/msm8996/audio hardware/qcom-caf/msm8996/display hardware/qcom-caf/msm8996/media
#git clone https://github.com/crdroidandroid/android_hardware_qcom_audio -b 11.0-caf-msm8996 hardware/qcom-caf/msm8996/audio --single-branch --depth=1
#git clone https://github.com/crdroidandroid/android_hardware_qcom_display -b 11.0-caf-msm8996 hardware/qcom-caf/msm8996/display --single-branch --depth=1
#git clone https://github.com/crdroidandroid/android_hardware_qcom_media -b 11.0-caf-msm8996 hardware/qcom-caf/msm8996/media --single-branch --depth=1
